language: php
php:
- 5.5
- 5.6
sudo: required
dist: trusty
addons:
  hosts:
  - riak-test
before_script:
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --prefer-source
- pushd vendor/allegro/protobuf
- phpize
- "./configure"
- make
- sudo make install
- popd
- echo 'extension = protobuf.so' >> "$HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini"
- php -m
- sudo ./tools/travis-ci/riak-install
- sudo ./tools/devrel/riak-cluster-config "$(which riak-admin)" 8098 false false
- riak version
notifications:
  slack:
    secure: C0dU3q6dHJF7ruMh7mdLMMpLWQAlGZZqKPt3f/uttN3/wI/JEBe5QTi1OtMqf6Id8kgk0KN9bnKCd2E2MOY4ZOGHic2bZc0RJTu3n1feS3UMXd0Ae5LIumLrwa1Sx0c5abSC+Al8cD+sBHeLIpGZoC/RMDTaZnHfPk20R/1CNZVO4LWsuScyAP+bGYM6DfeQhTzIefa/U8n7kULzKtpZ2uvYKWxtnYC8bPUEDzi+tp2uK8cepE+Qs411Byj5NshRnQ9OLcbvLsfr+DblY/OI0Jlkvsc/8OsnXm7s9S26ee6e9O0Y3AivE5/iB/UiOGkOTIwB2eC/H3NGh9zIXXDKWxmsJlblH1PMhJ5nD1ftdtqXsKUvXM68F5U9YLSoDiDzw6tW99QFQFTzL2SAZMlo25e0KRE0AeVptQRuLfBTdGauYuYJLR6A1LZxfLAQgl93whp0swPH9bp+SfifB4NGYf1OGe4DuM/P2T1hJGwmV4NkHlRM2OpJAesmyJMOhgeYYRXsmORQdih/5cYGQbm96ual+Pcfa/YVRhnl+GKyyX6CTyNGz6sVio/pAXB4GLRAWoo8/4YshA9TvlhFO+57iGlb8glwwhXRq9LS5AyydJxEeRFOxnrOGXrh2tNEjcSbqv7dX90fAtdeqhYIOUaLFwRNTUEMq3qNt9n6X6goivk=
script: "./vendor/bin/phpunit --coverage-text"
