<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RpbErrorResp extends \Google\Protobuf\Internal\Message
{
    private $errmsg = '';
    private $errcode = 0;

    public function getErrmsg()
    {
        return $this->errmsg;
    }

    public function setErrmsg($var)
    {
        GPBUtil::checkString($var, False);
        $this->errmsg = $var;
    }

    public function getErrcode()
    {
        return $this->errcode;
    }

    public function setErrcode($var)
    {
        GPBUtil::checkUint32($var);
        $this->errcode = $var;
    }

}

class RpbGetServerInfoResp extends \Google\Protobuf\Internal\Message
{
    private $node = '';
    private $server_version = '';

    public function getNode()
    {
        return $this->node;
    }

    public function setNode($var)
    {
        GPBUtil::checkString($var, False);
        $this->node = $var;
    }

    public function getServerVersion()
    {
        return $this->server_version;
    }

    public function setServerVersion($var)
    {
        GPBUtil::checkString($var, False);
        $this->server_version = $var;
    }

}

class RpbPair extends \Google\Protobuf\Internal\Message
{
    private $key = '';
    private $value = '';

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;
    }

}

class RpbGetBucketReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbGetBucketResp extends \Google\Protobuf\Internal\Message
{
    private $props = null;

    public function getProps()
    {
        return $this->props;
    }

    public function setProps(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps::class);
        $this->props = $var;
    }

}

class RpbSetBucketReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $props = null;
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getProps()
    {
        return $this->props;
    }

    public function setProps(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps::class);
        $this->props = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbResetBucketReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbGetBucketTypeReq extends \Google\Protobuf\Internal\Message
{
    private $type = '';

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbSetBucketTypeReq extends \Google\Protobuf\Internal\Message
{
    private $type = '';
    private $props = null;

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getProps()
    {
        return $this->props;
    }

    public function setProps(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps::class);
        $this->props = $var;
    }

}

class RpbModFun extends \Google\Protobuf\Internal\Message
{
    private $module = '';
    private $function = '';

    public function getModule()
    {
        return $this->module;
    }

    public function setModule($var)
    {
        GPBUtil::checkString($var, False);
        $this->module = $var;
    }

    public function getFunction()
    {
        return $this->function;
    }

    public function setFunction($var)
    {
        GPBUtil::checkString($var, False);
        $this->function = $var;
    }

}

class RpbCommitHook extends \Google\Protobuf\Internal\Message
{
    private $modfun = null;
    private $name = '';

    public function getModfun()
    {
        return $this->modfun;
    }

    public function setModfun(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbModFun::class);
        $this->modfun = $var;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;
    }

}

class RpbBucketProps extends \Google\Protobuf\Internal\Message
{
    private $n_val = 0;
    private $allow_mult = false;
    private $last_write_wins = false;
    private $precommit;
    private $has_precommit = false;
    private $postcommit;
    private $has_postcommit = false;
    private $chash_keyfun = null;
    private $linkfun = null;
    private $old_vclock = 0;
    private $young_vclock = 0;
    private $big_vclock = 0;
    private $small_vclock = 0;
    private $pr = 0;
    private $r = 0;
    private $w = 0;
    private $pw = 0;
    private $dw = 0;
    private $rw = 0;
    private $basic_quorum = false;
    private $notfound_ok = false;
    private $backend = '';
    private $search = false;
    private $repl = 0;
    private $search_index = '';
    private $datatype = '';
    private $consistent = false;
    private $write_once = false;
    private $hll_precision = 0;

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getAllowMult()
    {
        return $this->allow_mult;
    }

    public function setAllowMult($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_mult = $var;
    }

    public function getLastWriteWins()
    {
        return $this->last_write_wins;
    }

    public function setLastWriteWins($var)
    {
        GPBUtil::checkBool($var);
        $this->last_write_wins = $var;
    }

    public function getPrecommit()
    {
        return $this->precommit;
    }

    public function setPrecommit(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbCommitHook::class);
        $this->precommit = $var;
    }

    public function getHasPrecommit()
    {
        return $this->has_precommit;
    }

    public function setHasPrecommit($var)
    {
        GPBUtil::checkBool($var);
        $this->has_precommit = $var;
    }

    public function getPostcommit()
    {
        return $this->postcommit;
    }

    public function setPostcommit(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbCommitHook::class);
        $this->postcommit = $var;
    }

    public function getHasPostcommit()
    {
        return $this->has_postcommit;
    }

    public function setHasPostcommit($var)
    {
        GPBUtil::checkBool($var);
        $this->has_postcommit = $var;
    }

    public function getChashKeyfun()
    {
        return $this->chash_keyfun;
    }

    public function setChashKeyfun(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbModFun::class);
        $this->chash_keyfun = $var;
    }

    public function getLinkfun()
    {
        return $this->linkfun;
    }

    public function setLinkfun(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbModFun::class);
        $this->linkfun = $var;
    }

    public function getOldVclock()
    {
        return $this->old_vclock;
    }

    public function setOldVclock($var)
    {
        GPBUtil::checkUint32($var);
        $this->old_vclock = $var;
    }

    public function getYoungVclock()
    {
        return $this->young_vclock;
    }

    public function setYoungVclock($var)
    {
        GPBUtil::checkUint32($var);
        $this->young_vclock = $var;
    }

    public function getBigVclock()
    {
        return $this->big_vclock;
    }

    public function setBigVclock($var)
    {
        GPBUtil::checkUint32($var);
        $this->big_vclock = $var;
    }

    public function getSmallVclock()
    {
        return $this->small_vclock;
    }

    public function setSmallVclock($var)
    {
        GPBUtil::checkUint32($var);
        $this->small_vclock = $var;
    }

    public function getPr()
    {
        return $this->pr;
    }

    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;
    }

    public function getR()
    {
        return $this->r;
    }

    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;
    }

    public function getW()
    {
        return $this->w;
    }

    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;
    }

    public function getPw()
    {
        return $this->pw;
    }

    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;
    }

    public function getDw()
    {
        return $this->dw;
    }

    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;
    }

    public function getRw()
    {
        return $this->rw;
    }

    public function setRw($var)
    {
        GPBUtil::checkUint32($var);
        $this->rw = $var;
    }

    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    public function setBasicQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->basic_quorum = $var;
    }

    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    public function setNotfoundOk($var)
    {
        GPBUtil::checkBool($var);
        $this->notfound_ok = $var;
    }

    public function getBackend()
    {
        return $this->backend;
    }

    public function setBackend($var)
    {
        GPBUtil::checkString($var, False);
        $this->backend = $var;
    }

    public function getSearch()
    {
        return $this->search;
    }

    public function setSearch($var)
    {
        GPBUtil::checkBool($var);
        $this->search = $var;
    }

    public function getRepl()
    {
        return $this->repl;
    }

    public function setRepl($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps_RpbReplMode::class);
        $this->repl = $var;
    }

    public function getSearchIndex()
    {
        return $this->search_index;
    }

    public function setSearchIndex($var)
    {
        GPBUtil::checkString($var, False);
        $this->search_index = $var;
    }

    public function getDatatype()
    {
        return $this->datatype;
    }

    public function setDatatype($var)
    {
        GPBUtil::checkString($var, False);
        $this->datatype = $var;
    }

    public function getConsistent()
    {
        return $this->consistent;
    }

    public function setConsistent($var)
    {
        GPBUtil::checkBool($var);
        $this->consistent = $var;
    }

    public function getWriteOnce()
    {
        return $this->write_once;
    }

    public function setWriteOnce($var)
    {
        GPBUtil::checkBool($var);
        $this->write_once = $var;
    }

    public function getHllPrecision()
    {
        return $this->hll_precision;
    }

    public function setHllPrecision($var)
    {
        GPBUtil::checkUint32($var);
        $this->hll_precision = $var;
    }

}

class RpbBucketProps_RpbReplMode
{
    const FALSE = 0;
    const REALTIME = 1;
    const FULLSYNC = 2;
    const TRUE = 3;
}

class RpbAuthReq extends \Google\Protobuf\Internal\Message
{
    private $user = '';
    private $password = '';

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($var)
    {
        GPBUtil::checkString($var, False);
        $this->user = $var;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($var)
    {
        GPBUtil::checkString($var, False);
        $this->password = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0af90c0a0a7269616b2e70726f746f1219626173686f2e7269616b2e6170" .
    "692e70622e6d657373616765222f0a0c5270624572726f7252657370120e" .
    "0a066572726d736718012001280c120f0a07657272636f64651802200128" .
    "0d223c0a14527062476574536572766572496e666f52657370120c0a046e" .
    "6f646518012001280c12160a0e7365727665725f76657273696f6e180220" .
    "01280c22250a0752706250616972120b0a036b657918012001280c120d0a" .
    "0576616c756518022001280c222f0a0f5270624765744275636b65745265" .
    "71120e0a066275636b657418012001280c120c0a04747970651802200128" .
    "0c224c0a105270624765744275636b65745265737012380a0570726f7073" .
    "18012001280b32292e626173686f2e7269616b2e6170692e70622e6d6573" .
    "736167652e5270624275636b657450726f707322690a0f52706253657442" .
    "75636b6574526571120e0a066275636b657418012001280c12380a057072" .
    "6f707318022001280b32292e626173686f2e7269616b2e6170692e70622e" .
    "6d6573736167652e5270624275636b657450726f7073120c0a0474797065" .
    "18032001280c22310a1152706252657365744275636b6574526571120e0a" .
    "066275636b657418012001280c120c0a047479706518022001280c22230a" .
    "135270624765744275636b657454797065526571120c0a04747970651801" .
    "2001280c225d0a135270625365744275636b657454797065526571120c0a" .
    "047479706518012001280c12380a0570726f707318022001280b32292e62" .
    "6173686f2e7269616b2e6170692e70622e6d6573736167652e5270624275" .
    "636b657450726f7073222d0a095270624d6f6446756e120e0a066d6f6475" .
    "6c6518012001280c12100a0866756e6374696f6e18022001280c22530a0d" .
    "527062436f6d6d6974486f6f6b12340a066d6f6466756e18012001280b32" .
    "242e626173686f2e7269616b2e6170692e70622e6d6573736167652e5270" .
    "624d6f6446756e120c0a046e616d6518022001280c22bb060a0e52706242" .
    "75636b657450726f7073120d0a056e5f76616c18012001280d12120a0a61" .
    "6c6c6f775f6d756c7418022001280812170a0f6c6173745f77726974655f" .
    "77696e73180320012808123b0a09707265636f6d6d697418042003280b32" .
    "282e626173686f2e7269616b2e6170692e70622e6d6573736167652e5270" .
    "62436f6d6d6974486f6f6b12150a0d6861735f707265636f6d6d69741805" .
    "20012808123c0a0a706f7374636f6d6d697418062003280b32282e626173" .
    "686f2e7269616b2e6170692e70622e6d6573736167652e527062436f6d6d" .
    "6974486f6f6b12160a0e6861735f706f7374636f6d6d6974180720012808" .
    "123a0a0c63686173685f6b657966756e18082001280b32242e626173686f" .
    "2e7269616b2e6170692e70622e6d6573736167652e5270624d6f6446756e" .
    "12350a076c696e6b66756e18092001280b32242e626173686f2e7269616b" .
    "2e6170692e70622e6d6573736167652e5270624d6f6446756e12120a0a6f" .
    "6c645f76636c6f636b180a2001280d12140a0c796f756e675f76636c6f63" .
    "6b180b2001280d12120a0a6269675f76636c6f636b180c2001280d12140a" .
    "0c736d616c6c5f76636c6f636b180d2001280d120a0a027072180e200128" .
    "0d12090a0172180f2001280d12090a017718102001280d120a0a02707718" .
    "112001280d120a0a02647718122001280d120a0a02727718132001280d12" .
    "140a0c62617369635f71756f72756d18142001280812130a0b6e6f74666f" .
    "756e645f6f6b181520012808120f0a076261636b656e6418162001280c12" .
    "0e0a0673656172636818172001280812430a047265706c18182001280e32" .
    "352e626173686f2e7269616b2e6170692e70622e6d6573736167652e5270" .
    "624275636b657450726f70732e5270625265706c4d6f646512140a0c7365" .
    "617263685f696e64657818192001280c12100a086461746174797065181a" .
    "2001280c12120a0a636f6e73697374656e74181b2001280812120a0a7772" .
    "6974655f6f6e6365181c2001280812150a0d686c6c5f707265636973696f" .
    "6e181d2001280d223e0a0b5270625265706c4d6f646512090a0546414c53" .
    "451000120c0a085245414c54494d451001120c0a0846554c4c53594e4310" .
    "0212080a04545255451003222c0a0a52706241757468526571120c0a0475" .
    "73657218012001280c12100a0870617373776f726418022001280c42210a" .
    "17636f6d2e626173686f2e7269616b2e70726f746f62756642065269616b" .
    "5042620670726f746f33"
));

