<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_search.proto

namespace Basho\Riak\Api\Pb\Message;

require_once('riak.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RpbSearchDoc extends \Google\Protobuf\Internal\Message
{
    private $fields;

    public function getFields()
    {
        return $this->fields;
    }

    public function setFields(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->fields = $var;
    }

}

class RpbSearchQueryReq extends \Google\Protobuf\Internal\Message
{
    private $q = '';
    private $index = '';
    private $rows = 0;
    private $start = 0;
    private $sort = '';
    private $filter = '';
    private $df = '';
    private $op = '';
    private $fl;
    private $presort = '';

    public function getQ()
    {
        return $this->q;
    }

    public function setQ($var)
    {
        GPBUtil::checkString($var, False);
        $this->q = $var;
    }

    public function getIndex()
    {
        return $this->index;
    }

    public function setIndex($var)
    {
        GPBUtil::checkString($var, False);
        $this->index = $var;
    }

    public function getRows()
    {
        return $this->rows;
    }

    public function setRows($var)
    {
        GPBUtil::checkUint32($var);
        $this->rows = $var;
    }

    public function getStart()
    {
        return $this->start;
    }

    public function setStart($var)
    {
        GPBUtil::checkUint32($var);
        $this->start = $var;
    }

    public function getSort()
    {
        return $this->sort;
    }

    public function setSort($var)
    {
        GPBUtil::checkString($var, False);
        $this->sort = $var;
    }

    public function getFilter()
    {
        return $this->filter;
    }

    public function setFilter($var)
    {
        GPBUtil::checkString($var, False);
        $this->filter = $var;
    }

    public function getDf()
    {
        return $this->df;
    }

    public function setDf($var)
    {
        GPBUtil::checkString($var, False);
        $this->df = $var;
    }

    public function getOp()
    {
        return $this->op;
    }

    public function setOp($var)
    {
        GPBUtil::checkString($var, False);
        $this->op = $var;
    }

    public function getFl()
    {
        return $this->fl;
    }

    public function setFl(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->fl = $var;
    }

    public function getPresort()
    {
        return $this->presort;
    }

    public function setPresort($var)
    {
        GPBUtil::checkString($var, False);
        $this->presort = $var;
    }

}

class RpbSearchQueryResp extends \Google\Protobuf\Internal\Message
{
    private $docs;
    private $max_score = 0.0;
    private $num_found = 0;

    public function getDocs()
    {
        return $this->docs;
    }

    public function setDocs(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbSearchDoc::class);
        $this->docs = $var;
    }

    public function getMaxScore()
    {
        return $this->max_score;
    }

    public function setMaxScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_score = $var;
    }

    public function getNumFound()
    {
        return $this->num_found;
    }

    public function setNumFound($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_found = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ac2030a117269616b5f7365617263682e70726f746f1219626173686f2e" .
    "7269616b2e6170692e70622e6d6573736167651a0a7269616b2e70726f74" .
    "6f22420a0c527062536561726368446f6312320a066669656c6473180120" .
    "03280b32222e626173686f2e7269616b2e6170692e70622e6d6573736167" .
    "652e52706250616972229d010a1152706253656172636851756572795265" .
    "7112090a017118012001280c120d0a05696e64657818022001280c120c0a" .
    "04726f777318032001280d120d0a05737461727418042001280d120c0a04" .
    "736f727418052001280c120e0a0666696c74657218062001280c120a0a02" .
    "646618072001280c120a0a026f7018082001280c120a0a02666c18092003" .
    "280c120f0a07707265736f7274180a2001280c22710a1252706253656172" .
    "636851756572795265737012350a04646f637318012003280b32272e6261" .
    "73686f2e7269616b2e6170692e70622e6d6573736167652e527062536561" .
    "726368446f6312110a096d61785f73636f726518022001280212110a096e" .
    "756d5f666f756e6418032001280d42270a17636f6d2e626173686f2e7269" .
    "616b2e70726f746f627566420c5269616b5365617263685042620670726f" .
    "746f33"
));

