<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

require_once('riak.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class RpbGetClientIdResp extends \Google\Protobuf\Internal\Message
{
    private $client_id = '';

    public function getClientId()
    {
        return $this->client_id;
    }

    public function setClientId($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_id = $var;
    }

}

class RpbSetClientIdReq extends \Google\Protobuf\Internal\Message
{
    private $client_id = '';

    public function getClientId()
    {
        return $this->client_id;
    }

    public function setClientId($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_id = $var;
    }

}

class RpbGetReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $r = 0;
    private $pr = 0;
    private $basic_quorum = false;
    private $notfound_ok = false;
    private $if_modified = '';
    private $head = false;
    private $deletedvclock = false;
    private $timeout = 0;
    private $sloppy_quorum = false;
    private $n_val = 0;
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getR()
    {
        return $this->r;
    }

    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;
    }

    public function getPr()
    {
        return $this->pr;
    }

    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;
    }

    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    public function setBasicQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->basic_quorum = $var;
    }

    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    public function setNotfoundOk($var)
    {
        GPBUtil::checkBool($var);
        $this->notfound_ok = $var;
    }

    public function getIfModified()
    {
        return $this->if_modified;
    }

    public function setIfModified($var)
    {
        GPBUtil::checkString($var, False);
        $this->if_modified = $var;
    }

    public function getHead()
    {
        return $this->head;
    }

    public function setHead($var)
    {
        GPBUtil::checkBool($var);
        $this->head = $var;
    }

    public function getDeletedvclock()
    {
        return $this->deletedvclock;
    }

    public function setDeletedvclock($var)
    {
        GPBUtil::checkBool($var);
        $this->deletedvclock = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;
    }

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbGetResp extends \Google\Protobuf\Internal\Message
{
    private $content;
    private $vclock = '';
    private $unchanged = false;

    public function getContent()
    {
        return $this->content;
    }

    public function setContent(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbContent::class);
        $this->content = $var;
    }

    public function getVclock()
    {
        return $this->vclock;
    }

    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;
    }

    public function getUnchanged()
    {
        return $this->unchanged;
    }

    public function setUnchanged($var)
    {
        GPBUtil::checkBool($var);
        $this->unchanged = $var;
    }

}

class RpbPutReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $vclock = '';
    private $content = null;
    private $w = 0;
    private $dw = 0;
    private $return_body = false;
    private $pw = 0;
    private $if_not_modified = false;
    private $if_none_match = false;
    private $return_head = false;
    private $timeout = 0;
    private $asis = false;
    private $sloppy_quorum = false;
    private $n_val = 0;
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getVclock()
    {
        return $this->vclock;
    }

    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbContent::class);
        $this->content = $var;
    }

    public function getW()
    {
        return $this->w;
    }

    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;
    }

    public function getDw()
    {
        return $this->dw;
    }

    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;
    }

    public function getReturnBody()
    {
        return $this->return_body;
    }

    public function setReturnBody($var)
    {
        GPBUtil::checkBool($var);
        $this->return_body = $var;
    }

    public function getPw()
    {
        return $this->pw;
    }

    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;
    }

    public function getIfNotModified()
    {
        return $this->if_not_modified;
    }

    public function setIfNotModified($var)
    {
        GPBUtil::checkBool($var);
        $this->if_not_modified = $var;
    }

    public function getIfNoneMatch()
    {
        return $this->if_none_match;
    }

    public function setIfNoneMatch($var)
    {
        GPBUtil::checkBool($var);
        $this->if_none_match = $var;
    }

    public function getReturnHead()
    {
        return $this->return_head;
    }

    public function setReturnHead($var)
    {
        GPBUtil::checkBool($var);
        $this->return_head = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getAsis()
    {
        return $this->asis;
    }

    public function setAsis($var)
    {
        GPBUtil::checkBool($var);
        $this->asis = $var;
    }

    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;
    }

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbPutResp extends \Google\Protobuf\Internal\Message
{
    private $content;
    private $vclock = '';
    private $key = '';

    public function getContent()
    {
        return $this->content;
    }

    public function setContent(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbContent::class);
        $this->content = $var;
    }

    public function getVclock()
    {
        return $this->vclock;
    }

    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

}

class RpbDelReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $rw = 0;
    private $vclock = '';
    private $r = 0;
    private $w = 0;
    private $pr = 0;
    private $pw = 0;
    private $dw = 0;
    private $timeout = 0;
    private $sloppy_quorum = false;
    private $n_val = 0;
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getRw()
    {
        return $this->rw;
    }

    public function setRw($var)
    {
        GPBUtil::checkUint32($var);
        $this->rw = $var;
    }

    public function getVclock()
    {
        return $this->vclock;
    }

    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;
    }

    public function getR()
    {
        return $this->r;
    }

    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;
    }

    public function getW()
    {
        return $this->w;
    }

    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;
    }

    public function getPr()
    {
        return $this->pr;
    }

    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;
    }

    public function getPw()
    {
        return $this->pw;
    }

    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;
    }

    public function getDw()
    {
        return $this->dw;
    }

    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;
    }

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbListBucketsReq extends \Google\Protobuf\Internal\Message
{
    private $timeout = 0;
    private $stream = false;
    private $type = '';

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getStream()
    {
        return $this->stream;
    }

    public function setStream($var)
    {
        GPBUtil::checkBool($var);
        $this->stream = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbListBucketsResp extends \Google\Protobuf\Internal\Message
{
    private $buckets;
    private $done = false;

    public function getBuckets()
    {
        return $this->buckets;
    }

    public function setBuckets(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->buckets = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbListKeysReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $timeout = 0;
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbListKeysResp extends \Google\Protobuf\Internal\Message
{
    private $keys;
    private $done = false;

    public function getKeys()
    {
        return $this->keys;
    }

    public function setKeys(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->keys = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbMapRedReq extends \Google\Protobuf\Internal\Message
{
    private $request = '';
    private $content_type = '';

    public function getRequest()
    {
        return $this->request;
    }

    public function setRequest($var)
    {
        GPBUtil::checkString($var, False);
        $this->request = $var;
    }

    public function getContentType()
    {
        return $this->content_type;
    }

    public function setContentType($var)
    {
        GPBUtil::checkString($var, False);
        $this->content_type = $var;
    }

}

class RpbMapRedResp extends \Google\Protobuf\Internal\Message
{
    private $phase = 0;
    private $response = '';
    private $done = false;

    public function getPhase()
    {
        return $this->phase;
    }

    public function setPhase($var)
    {
        GPBUtil::checkUint32($var);
        $this->phase = $var;
    }

    public function getResponse()
    {
        return $this->response;
    }

    public function setResponse($var)
    {
        GPBUtil::checkString($var, False);
        $this->response = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbIndexReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $index = '';
    private $qtype = 0;
    private $key = '';
    private $range_min = '';
    private $range_max = '';
    private $return_terms = false;
    private $stream = false;
    private $max_results = 0;
    private $continuation = '';
    private $timeout = 0;
    private $type = '';
    private $term_regex = '';
    private $pagination_sort = false;
    private $cover_context = '';
    private $return_body = false;

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getIndex()
    {
        return $this->index;
    }

    public function setIndex($var)
    {
        GPBUtil::checkString($var, False);
        $this->index = $var;
    }

    public function getQtype()
    {
        return $this->qtype;
    }

    public function setQtype($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\RpbIndexReq_IndexQueryType::class);
        $this->qtype = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getRangeMin()
    {
        return $this->range_min;
    }

    public function setRangeMin($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_min = $var;
    }

    public function getRangeMax()
    {
        return $this->range_max;
    }

    public function setRangeMax($var)
    {
        GPBUtil::checkString($var, False);
        $this->range_max = $var;
    }

    public function getReturnTerms()
    {
        return $this->return_terms;
    }

    public function setReturnTerms($var)
    {
        GPBUtil::checkBool($var);
        $this->return_terms = $var;
    }

    public function getStream()
    {
        return $this->stream;
    }

    public function setStream($var)
    {
        GPBUtil::checkBool($var);
        $this->stream = $var;
    }

    public function getMaxResults()
    {
        return $this->max_results;
    }

    public function setMaxResults($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_results = $var;
    }

    public function getContinuation()
    {
        return $this->continuation;
    }

    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getTermRegex()
    {
        return $this->term_regex;
    }

    public function setTermRegex($var)
    {
        GPBUtil::checkString($var, False);
        $this->term_regex = $var;
    }

    public function getPaginationSort()
    {
        return $this->pagination_sort;
    }

    public function setPaginationSort($var)
    {
        GPBUtil::checkBool($var);
        $this->pagination_sort = $var;
    }

    public function getCoverContext()
    {
        return $this->cover_context;
    }

    public function setCoverContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->cover_context = $var;
    }

    public function getReturnBody()
    {
        return $this->return_body;
    }

    public function setReturnBody($var)
    {
        GPBUtil::checkBool($var);
        $this->return_body = $var;
    }

}

class RpbIndexReq_IndexQueryType
{
    const eq = 0;
    const range = 1;
}

class RpbIndexResp extends \Google\Protobuf\Internal\Message
{
    private $keys;
    private $results;
    private $continuation = '';
    private $done = false;

    public function getKeys()
    {
        return $this->keys;
    }

    public function setKeys(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->keys = $var;
    }

    public function getResults()
    {
        return $this->results;
    }

    public function setResults(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->results = $var;
    }

    public function getContinuation()
    {
        return $this->continuation;
    }

    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbIndexBodyResp extends \Google\Protobuf\Internal\Message
{
    private $objects;
    private $continuation = '';
    private $done = false;

    public function getObjects()
    {
        return $this->objects;
    }

    public function setObjects(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbIndexObject::class);
        $this->objects = $var;
    }

    public function getContinuation()
    {
        return $this->continuation;
    }

    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbCSBucketReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $start_key = '';
    private $end_key = '';
    private $start_incl = false;
    private $end_incl = false;
    private $continuation = '';
    private $max_results = 0;
    private $timeout = 0;
    private $type = '';
    private $cover_context = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getStartKey()
    {
        return $this->start_key;
    }

    public function setStartKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->start_key = $var;
    }

    public function getEndKey()
    {
        return $this->end_key;
    }

    public function setEndKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->end_key = $var;
    }

    public function getStartIncl()
    {
        return $this->start_incl;
    }

    public function setStartIncl($var)
    {
        GPBUtil::checkBool($var);
        $this->start_incl = $var;
    }

    public function getEndIncl()
    {
        return $this->end_incl;
    }

    public function setEndIncl($var)
    {
        GPBUtil::checkBool($var);
        $this->end_incl = $var;
    }

    public function getContinuation()
    {
        return $this->continuation;
    }

    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;
    }

    public function getMaxResults()
    {
        return $this->max_results;
    }

    public function setMaxResults($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_results = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getCoverContext()
    {
        return $this->cover_context;
    }

    public function setCoverContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->cover_context = $var;
    }

}

class RpbCSBucketResp extends \Google\Protobuf\Internal\Message
{
    private $objects;
    private $continuation = '';
    private $done = false;

    public function getObjects()
    {
        return $this->objects;
    }

    public function setObjects(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbIndexObject::class);
        $this->objects = $var;
    }

    public function getContinuation()
    {
        return $this->continuation;
    }

    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class RpbIndexObject extends \Google\Protobuf\Internal\Message
{
    private $key = '';
    private $object = null;

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getObject()
    {
        return $this->object;
    }

    public function setObject(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbGetResp::class);
        $this->object = $var;
    }

}

class RpbContent extends \Google\Protobuf\Internal\Message
{
    private $value = '';
    private $content_type = '';
    private $charset = '';
    private $content_encoding = '';
    private $vtag = '';
    private $links;
    private $last_mod = 0;
    private $last_mod_usecs = 0;
    private $usermeta;
    private $indexes;
    private $deleted = false;

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;
    }

    public function getContentType()
    {
        return $this->content_type;
    }

    public function setContentType($var)
    {
        GPBUtil::checkString($var, False);
        $this->content_type = $var;
    }

    public function getCharset()
    {
        return $this->charset;
    }

    public function setCharset($var)
    {
        GPBUtil::checkString($var, False);
        $this->charset = $var;
    }

    public function getContentEncoding()
    {
        return $this->content_encoding;
    }

    public function setContentEncoding($var)
    {
        GPBUtil::checkString($var, False);
        $this->content_encoding = $var;
    }

    public function getVtag()
    {
        return $this->vtag;
    }

    public function setVtag($var)
    {
        GPBUtil::checkString($var, False);
        $this->vtag = $var;
    }

    public function getLinks()
    {
        return $this->links;
    }

    public function setLinks(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbLink::class);
        $this->links = $var;
    }

    public function getLastMod()
    {
        return $this->last_mod;
    }

    public function setLastMod($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_mod = $var;
    }

    public function getLastModUsecs()
    {
        return $this->last_mod_usecs;
    }

    public function setLastModUsecs($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_mod_usecs = $var;
    }

    public function getUsermeta()
    {
        return $this->usermeta;
    }

    public function setUsermeta(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->usermeta = $var;
    }

    public function getIndexes()
    {
        return $this->indexes;
    }

    public function setIndexes(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->indexes = $var;
    }

    public function getDeleted()
    {
        return $this->deleted;
    }

    public function setDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->deleted = $var;
    }

}

class RpbLink extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $tag = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getTag()
    {
        return $this->tag;
    }

    public function setTag($var)
    {
        GPBUtil::checkString($var, False);
        $this->tag = $var;
    }

}

class RpbCounterUpdateReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $amount = 0;
    private $w = 0;
    private $dw = 0;
    private $pw = 0;
    private $returnvalue = false;

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getAmount()
    {
        return $this->amount;
    }

    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;
    }

    public function getW()
    {
        return $this->w;
    }

    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;
    }

    public function getDw()
    {
        return $this->dw;
    }

    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;
    }

    public function getPw()
    {
        return $this->pw;
    }

    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;
    }

    public function getReturnvalue()
    {
        return $this->returnvalue;
    }

    public function setReturnvalue($var)
    {
        GPBUtil::checkBool($var);
        $this->returnvalue = $var;
    }

}

class RpbCounterUpdateResp extends \Google\Protobuf\Internal\Message
{
    private $value = 0;

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;
    }

}

class RpbCounterGetReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $r = 0;
    private $pr = 0;
    private $basic_quorum = false;
    private $notfound_ok = false;

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getR()
    {
        return $this->r;
    }

    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;
    }

    public function getPr()
    {
        return $this->pr;
    }

    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;
    }

    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    public function setBasicQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->basic_quorum = $var;
    }

    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    public function setNotfoundOk($var)
    {
        GPBUtil::checkBool($var);
        $this->notfound_ok = $var;
    }

}

class RpbCounterGetResp extends \Google\Protobuf\Internal\Message
{
    private $value = 0;

    public function getValue()
    {
        return $this->value;
    }

    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;
    }

}

class RpbGetBucketKeyPreflistReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $type = '';

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

}

class RpbGetBucketKeyPreflistResp extends \Google\Protobuf\Internal\Message
{
    private $preflist;

    public function getPreflist()
    {
        return $this->preflist;
    }

    public function setPreflist(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbBucketKeyPreflistItem::class);
        $this->preflist = $var;
    }

}

class RpbBucketKeyPreflistItem extends \Google\Protobuf\Internal\Message
{
    private $partition = 0;
    private $node = '';
    private $primary = false;

    public function getPartition()
    {
        return $this->partition;
    }

    public function setPartition($var)
    {
        GPBUtil::checkInt64($var);
        $this->partition = $var;
    }

    public function getNode()
    {
        return $this->node;
    }

    public function setNode($var)
    {
        GPBUtil::checkString($var, False);
        $this->node = $var;
    }

    public function getPrimary()
    {
        return $this->primary;
    }

    public function setPrimary($var)
    {
        GPBUtil::checkBool($var);
        $this->primary = $var;
    }

}

class RpbCoverageReq extends \Google\Protobuf\Internal\Message
{
    private $type = '';
    private $bucket = '';
    private $min_partitions = 0;
    private $replace_cover = '';
    private $unavailable_cover;

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getMinPartitions()
    {
        return $this->min_partitions;
    }

    public function setMinPartitions($var)
    {
        GPBUtil::checkUint32($var);
        $this->min_partitions = $var;
    }

    public function getReplaceCover()
    {
        return $this->replace_cover;
    }

    public function setReplaceCover($var)
    {
        GPBUtil::checkString($var, False);
        $this->replace_cover = $var;
    }

    public function getUnavailableCover()
    {
        return $this->unavailable_cover;
    }

    public function setUnavailableCover(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->unavailable_cover = $var;
    }

}

class RpbCoverageResp extends \Google\Protobuf\Internal\Message
{
    private $entries;

    public function getEntries()
    {
        return $this->entries;
    }

    public function setEntries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbCoverageEntry::class);
        $this->entries = $var;
    }

}

class RpbCoverageEntry extends \Google\Protobuf\Internal\Message
{
    private $ip = '';
    private $port = 0;
    private $keyspace_desc = '';
    private $cover_context = '';

    public function getIp()
    {
        return $this->ip;
    }

    public function setIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->ip = $var;
    }

    public function getPort()
    {
        return $this->port;
    }

    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;
    }

    public function getKeyspaceDesc()
    {
        return $this->keyspace_desc;
    }

    public function setKeyspaceDesc($var)
    {
        GPBUtil::checkString($var, False);
        $this->keyspace_desc = $var;
    }

    public function getCoverContext()
    {
        return $this->cover_context;
    }

    public function setCoverContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->cover_context = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0ac61d0a0d7269616b5f6b762e70726f746f1219626173686f2e7269616b" .
    "2e6170692e70622e6d6573736167651a0a7269616b2e70726f746f22270a" .
    "12527062476574436c69656e7449645265737012110a09636c69656e745f" .
    "696418012001280c22260a11527062536574436c69656e74496452657112" .
    "110a09636c69656e745f696418012001280c22e9010a0952706247657452" .
    "6571120e0a066275636b657418012001280c120b0a036b65791802200128" .
    "0c12090a017218032001280d120a0a02707218042001280d12140a0c6261" .
    "7369635f71756f72756d18052001280812130a0b6e6f74666f756e645f6f" .
    "6b18062001280812130a0b69665f6d6f64696669656418072001280c120c" .
    "0a046865616418082001280812150a0d64656c6574656476636c6f636b18" .
    "0920012808120f0a0774696d656f7574180a2001280d12150a0d736c6f70" .
    "70795f71756f72756d180b20012808120d0a056e5f76616c180c2001280d" .
    "120c0a0474797065180d2001280c22670a0a527062476574526573701236" .
    "0a07636f6e74656e7418012003280b32252e626173686f2e7269616b2e61" .
    "70692e70622e6d6573736167652e527062436f6e74656e74120e0a067663" .
    "6c6f636b18022001280c12110a09756e6368616e67656418032001280822" .
    "c0020a09527062507574526571120e0a066275636b657418012001280c12" .
    "0b0a036b657918022001280c120e0a0676636c6f636b18032001280c1236" .
    "0a07636f6e74656e7418042001280b32252e626173686f2e7269616b2e61" .
    "70692e70622e6d6573736167652e527062436f6e74656e7412090a017718" .
    "052001280d120a0a02647718062001280d12130a0b72657475726e5f626f" .
    "6479180720012808120a0a02707718082001280d12170a0f69665f6e6f74" .
    "5f6d6f64696669656418092001280812150a0d69665f6e6f6e655f6d6174" .
    "6368180a2001280812130a0b72657475726e5f68656164180b2001280812" .
    "0f0a0774696d656f7574180c2001280d120c0a0461736973180d20012808" .
    "12150a0d736c6f7070795f71756f72756d180e20012808120d0a056e5f76" .
    "616c180f2001280d120c0a047479706518102001280c22610a0a52706250" .
    "75745265737012360a07636f6e74656e7418012003280b32252e62617368" .
    "6f2e7269616b2e6170692e70622e6d6573736167652e527062436f6e7465" .
    "6e74120e0a0676636c6f636b18022001280c120b0a036b65791803200128" .
    "0c22c3010a0952706244656c526571120e0a066275636b65741801200128" .
    "0c120b0a036b657918022001280c120a0a02727718032001280d120e0a06" .
    "76636c6f636b18042001280c12090a017218052001280d12090a01771806" .
    "2001280d120a0a02707218072001280d120a0a02707718082001280d120a" .
    "0a02647718092001280d120f0a0774696d656f7574180a2001280d12150a" .
    "0d736c6f7070795f71756f72756d180b20012808120d0a056e5f76616c18" .
    "0c2001280d120c0a0474797065180d2001280c22420a115270624c697374" .
    "4275636b657473526571120f0a0774696d656f757418012001280d120e0a" .
    "0673747265616d180220012808120c0a047479706518032001280c22330a" .
    "125270624c6973744275636b65747352657370120f0a076275636b657473" .
    "18012003280c120c0a04646f6e65180220012808223f0a0e5270624c6973" .
    "744b657973526571120e0a066275636b657418012001280c120f0a077469" .
    "6d656f757418022001280d120c0a047479706518032001280c222d0a0f52" .
    "70624c6973744b65797352657370120c0a046b65797318012003280c120c" .
    "0a04646f6e6518022001280822350a0c5270624d6170526564526571120f" .
    "0a077265717565737418012001280c12140a0c636f6e74656e745f747970" .
    "6518022001280c223e0a0d5270624d617052656452657370120d0a057068" .
    "61736518012001280d12100a08726573706f6e736518022001280c120c0a" .
    "04646f6e651803200128082293030a0b527062496e646578526571120e0a" .
    "066275636b657418012001280c120d0a05696e64657818022001280c1244" .
    "0a05717479706518032001280e32352e626173686f2e7269616b2e617069" .
    "2e70622e6d6573736167652e527062496e6465785265712e496e64657851" .
    "7565727954797065120b0a036b657918042001280c12110a0972616e6765" .
    "5f6d696e18052001280c12110a0972616e67655f6d617818062001280c12" .
    "140a0c72657475726e5f7465726d73180720012808120e0a067374726561" .
    "6d18082001280812130a0b6d61785f726573756c747318092001280d1214" .
    "0a0c636f6e74696e756174696f6e180a2001280c120f0a0774696d656f75" .
    "74180b2001280d120c0a0474797065180c2001280c12120a0a7465726d5f" .
    "7265676578180d2001280c12170a0f706167696e6174696f6e5f736f7274" .
    "180e2001280812150a0d636f7665725f636f6e74657874180f2001280c12" .
    "130a0b72657475726e5f626f647918102001280822230a0e496e64657851" .
    "756572795479706512060a026571100012090a0572616e6765100122750a" .
    "0c527062496e64657852657370120c0a046b65797318012003280c12330a" .
    "07726573756c747318022003280b32222e626173686f2e7269616b2e6170" .
    "692e70622e6d6573736167652e5270625061697212140a0c636f6e74696e" .
    "756174696f6e18032001280c120c0a04646f6e6518042001280822720a10" .
    "527062496e646578426f647952657370123a0a076f626a65637473180120" .
    "03280b32292e626173686f2e7269616b2e6170692e70622e6d6573736167" .
    "652e527062496e6465784f626a65637412140a0c636f6e74696e75617469" .
    "6f6e18022001280c120c0a04646f6e6518032001280822cb010a0e527062" .
    "43534275636b6574526571120e0a066275636b657418012001280c12110a" .
    "0973746172745f6b657918022001280c120f0a07656e645f6b6579180320" .
    "01280c12120a0a73746172745f696e636c18042001280812100a08656e64" .
    "5f696e636c18052001280812140a0c636f6e74696e756174696f6e180620" .
    "01280c12130a0b6d61785f726573756c747318072001280d120f0a077469" .
    "6d656f757418082001280d120c0a047479706518092001280c12150a0d63" .
    "6f7665725f636f6e74657874180a2001280c22710a0f5270624353427563" .
    "6b657452657370123a0a076f626a6563747318012003280b32292e626173" .
    "686f2e7269616b2e6170692e70622e6d6573736167652e527062496e6465" .
    "784f626a65637412140a0c636f6e74696e756174696f6e18022001280c12" .
    "0c0a04646f6e6518032001280822540a0e527062496e6465784f626a6563" .
    "74120b0a036b657918012001280c12350a066f626a65637418022001280b" .
    "32252e626173686f2e7269616b2e6170692e70622e6d6573736167652e52" .
    "70624765745265737022c3020a0a527062436f6e74656e74120d0a057661" .
    "6c756518012001280c12140a0c636f6e74656e745f747970651802200128" .
    "0c120f0a076368617273657418032001280c12180a10636f6e74656e745f" .
    "656e636f64696e6718042001280c120c0a047674616718052001280c1231" .
    "0a056c696e6b7318062003280b32222e626173686f2e7269616b2e617069" .
    "2e70622e6d6573736167652e5270624c696e6b12100a086c6173745f6d6f" .
    "6418072001280d12160a0e6c6173745f6d6f645f75736563731808200128" .
    "0d12340a08757365726d65746118092003280b32222e626173686f2e7269" .
    "616b2e6170692e70622e6d6573736167652e5270625061697212330a0769" .
    "6e6465786573180a2003280b32222e626173686f2e7269616b2e6170692e" .
    "70622e6d6573736167652e52706250616972120f0a0764656c6574656418" .
    "0b2001280822330a075270624c696e6b120e0a066275636b657418012001" .
    "280c120b0a036b657918022001280c120b0a0374616718032001280c227a" .
    "0a13527062436f756e746572557064617465526571120e0a066275636b65" .
    "7418012001280c120b0a036b657918022001280c120e0a06616d6f756e74" .
    "18032001281212090a017718042001280d120a0a02647718052001280d12" .
    "0a0a02707718062001280d12130a0b72657475726e76616c756518072001" .
    "280822250a14527062436f756e74657255706461746552657370120d0a05" .
    "76616c756518012001281222710a10527062436f756e7465724765745265" .
    "71120e0a066275636b657418012001280c120b0a036b657918022001280c" .
    "12090a017218032001280d120a0a02707218042001280d12140a0c626173" .
    "69635f71756f72756d18052001280812130a0b6e6f74666f756e645f6f6b" .
    "18062001280822220a11527062436f756e74657247657452657370120d0a" .
    "0576616c756518012001281222470a1a5270624765744275636b65744b65" .
    "79507265666c697374526571120e0a066275636b657418012001280c120b" .
    "0a036b657918022001280c120c0a047479706518032001280c22640a1b52" .
    "70624765744275636b65744b6579507265666c6973745265737012450a08" .
    "707265666c69737418012003280b32332e626173686f2e7269616b2e6170" .
    "692e70622e6d6573736167652e5270624275636b65744b6579507265666c" .
    "6973744974656d224c0a185270624275636b65744b6579507265666c6973" .
    "744974656d12110a09706172746974696f6e180120012803120c0a046e6f" .
    "646518022001280c120f0a077072696d61727918032001280822780a0e52" .
    "7062436f766572616765526571120c0a047479706518012001280c120e0a" .
    "066275636b657418022001280c12160a0e6d696e5f706172746974696f6e" .
    "7318032001280d12150a0d7265706c6163655f636f76657218042001280c" .
    "12190a11756e617661696c61626c655f636f76657218052003280c224f0a" .
    "0f527062436f76657261676552657370123c0a07656e7472696573180120" .
    "03280b322b2e626173686f2e7269616b2e6170692e70622e6d6573736167" .
    "652e527062436f766572616765456e747279225a0a10527062436f766572" .
    "616765456e747279120a0a02697018012001280c120c0a04706f72741802" .
    "2001280d12150a0d6b657973706163655f6465736318032001280c12150a" .
    "0d636f7665725f636f6e7465787418042001280c42230a17636f6d2e6261" .
    "73686f2e7269616b2e70726f746f62756642085269616b4b765042620670" .
    "726f746f33"
));

