<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_ts.proto

namespace Basho\Riak\Api\Pb\Message;

require_once('riak.pb.php');
use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class TsQueryReq extends \Google\Protobuf\Internal\Message
{
    private $query = null;
    private $stream = false;
    private $cover_context = '';

    public function getQuery()
    {
        return $this->query;
    }

    public function setQuery(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\TsInterpolation::class);
        $this->query = $var;
    }

    public function getStream()
    {
        return $this->stream;
    }

    public function setStream($var)
    {
        GPBUtil::checkBool($var);
        $this->stream = $var;
    }

    public function getCoverContext()
    {
        return $this->cover_context;
    }

    public function setCoverContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->cover_context = $var;
    }

}

class TsQueryResp extends \Google\Protobuf\Internal\Message
{
    private $columns;
    private $rows;
    private $done = false;

    public function getColumns()
    {
        return $this->columns;
    }

    public function setColumns(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsColumnDescription::class);
        $this->columns = $var;
    }

    public function getRows()
    {
        return $this->rows;
    }

    public function setRows(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->rows = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class TsGetReq extends \Google\Protobuf\Internal\Message
{
    private $table = '';
    private $key;
    private $timeout = 0;

    public function getTable()
    {
        return $this->table;
    }

    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsCell::class);
        $this->key = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

}

class TsGetResp extends \Google\Protobuf\Internal\Message
{
    private $columns;
    private $rows;

    public function getColumns()
    {
        return $this->columns;
    }

    public function setColumns(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsColumnDescription::class);
        $this->columns = $var;
    }

    public function getRows()
    {
        return $this->rows;
    }

    public function setRows(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->rows = $var;
    }

}

class TsPutReq extends \Google\Protobuf\Internal\Message
{
    private $table = '';
    private $columns;
    private $rows;

    public function getTable()
    {
        return $this->table;
    }

    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;
    }

    public function getColumns()
    {
        return $this->columns;
    }

    public function setColumns(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsColumnDescription::class);
        $this->columns = $var;
    }

    public function getRows()
    {
        return $this->rows;
    }

    public function setRows(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->rows = $var;
    }

}

class TsPutResp extends \Google\Protobuf\Internal\Message
{

}

class TsDelReq extends \Google\Protobuf\Internal\Message
{
    private $table = '';
    private $key;
    private $vclock = '';
    private $timeout = 0;

    public function getTable()
    {
        return $this->table;
    }

    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsCell::class);
        $this->key = $var;
    }

    public function getVclock()
    {
        return $this->vclock;
    }

    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

}

class TsDelResp extends \Google\Protobuf\Internal\Message
{

}

class TsInterpolation extends \Google\Protobuf\Internal\Message
{
    private $base = '';
    private $interpolations;

    public function getBase()
    {
        return $this->base;
    }

    public function setBase($var)
    {
        GPBUtil::checkString($var, False);
        $this->base = $var;
    }

    public function getInterpolations()
    {
        return $this->interpolations;
    }

    public function setInterpolations(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->interpolations = $var;
    }

}

class TsColumnDescription extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $type = 0;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\TsColumnType::class);
        $this->type = $var;
    }

}

class TsRow extends \Google\Protobuf\Internal\Message
{
    private $cells;

    public function getCells()
    {
        return $this->cells;
    }

    public function setCells(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsCell::class);
        $this->cells = $var;
    }

}

class TsCell extends \Google\Protobuf\Internal\Message
{
    private $varchar_value = '';
    private $sint64_value = 0;
    private $timestamp_value = 0;
    private $boolean_value = false;
    private $double_value = 0.0;

    public function getVarcharValue()
    {
        return $this->varchar_value;
    }

    public function setVarcharValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->varchar_value = $var;
    }

    public function getSint64Value()
    {
        return $this->sint64_value;
    }

    public function setSint64Value($var)
    {
        GPBUtil::checkInt64($var);
        $this->sint64_value = $var;
    }

    public function getTimestampValue()
    {
        return $this->timestamp_value;
    }

    public function setTimestampValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp_value = $var;
    }

    public function getBooleanValue()
    {
        return $this->boolean_value;
    }

    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->boolean_value = $var;
    }

    public function getDoubleValue()
    {
        return $this->double_value;
    }

    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_value = $var;
    }

}

class TsListKeysReq extends \Google\Protobuf\Internal\Message
{
    private $table = '';
    private $timeout = 0;

    public function getTable()
    {
        return $this->table;
    }

    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

}

class TsListKeysResp extends \Google\Protobuf\Internal\Message
{
    private $keys;
    private $done = false;

    public function getKeys()
    {
        return $this->keys;
    }

    public function setKeys(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->keys = $var;
    }

    public function getDone()
    {
        return $this->done;
    }

    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;
    }

}

class TsCoverageReq extends \Google\Protobuf\Internal\Message
{
    private $query = null;
    private $table = '';
    private $replace_cover = '';
    private $unavailable_cover;

    public function getQuery()
    {
        return $this->query;
    }

    public function setQuery(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\TsInterpolation::class);
        $this->query = $var;
    }

    public function getTable()
    {
        return $this->table;
    }

    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;
    }

    public function getReplaceCover()
    {
        return $this->replace_cover;
    }

    public function setReplaceCover($var)
    {
        GPBUtil::checkString($var, False);
        $this->replace_cover = $var;
    }

    public function getUnavailableCover()
    {
        return $this->unavailable_cover;
    }

    public function setUnavailableCover(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->unavailable_cover = $var;
    }

}

class TsCoverageResp extends \Google\Protobuf\Internal\Message
{
    private $entries;

    public function getEntries()
    {
        return $this->entries;
    }

    public function setEntries(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsCoverageEntry::class);
        $this->entries = $var;
    }

}

class TsCoverageEntry extends \Google\Protobuf\Internal\Message
{
    private $ip = '';
    private $port = 0;
    private $cover_context = '';
    private $range = null;

    public function getIp()
    {
        return $this->ip;
    }

    public function setIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->ip = $var;
    }

    public function getPort()
    {
        return $this->port;
    }

    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;
    }

    public function getCoverContext()
    {
        return $this->cover_context;
    }

    public function setCoverContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->cover_context = $var;
    }

    public function getRange()
    {
        return $this->range;
    }

    public function setRange(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\TsRange::class);
        $this->range = $var;
    }

}

class TsRange extends \Google\Protobuf\Internal\Message
{
    private $field_name = '';
    private $lower_bound = 0;
    private $lower_bound_inclusive = false;
    private $upper_bound = 0;
    private $upper_bound_inclusive = false;
    private $desc = '';

    public function getFieldName()
    {
        return $this->field_name;
    }

    public function setFieldName($var)
    {
        GPBUtil::checkString($var, False);
        $this->field_name = $var;
    }

    public function getLowerBound()
    {
        return $this->lower_bound;
    }

    public function setLowerBound($var)
    {
        GPBUtil::checkInt64($var);
        $this->lower_bound = $var;
    }

    public function getLowerBoundInclusive()
    {
        return $this->lower_bound_inclusive;
    }

    public function setLowerBoundInclusive($var)
    {
        GPBUtil::checkBool($var);
        $this->lower_bound_inclusive = $var;
    }

    public function getUpperBound()
    {
        return $this->upper_bound;
    }

    public function setUpperBound($var)
    {
        GPBUtil::checkInt64($var);
        $this->upper_bound = $var;
    }

    public function getUpperBoundInclusive()
    {
        return $this->upper_bound_inclusive;
    }

    public function setUpperBoundInclusive($var)
    {
        GPBUtil::checkBool($var);
        $this->upper_bound_inclusive = $var;
    }

    public function getDesc()
    {
        return $this->desc;
    }

    public function setDesc($var)
    {
        GPBUtil::checkString($var, False);
        $this->desc = $var;
    }

}

class TsColumnType
{
    const VARCHAR = 0;
    const SINT64 = 1;
    const DOUBLE = 2;
    const TIMESTAMP = 3;
    const BOOLEAN = 4;
}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0afc0e0a0d7269616b5f74732e70726f746f1219626173686f2e7269616b" .
    "2e6170692e70622e6d6573736167651a0a7269616b2e70726f746f226e0a" .
    "0a5473517565727952657112390a05717565727918012001280b322a2e62" .
    "6173686f2e7269616b2e6170692e70622e6d6573736167652e5473496e74" .
    "6572706f6c6174696f6e120e0a0673747265616d18022001280812150a0d" .
    "636f7665725f636f6e7465787418032001280c228c010a0b547351756572" .
    "7952657370123f0a07636f6c756d6e7318012003280b322e2e626173686f" .
    "2e7269616b2e6170692e70622e6d6573736167652e5473436f6c756d6e44" .
    "65736372697074696f6e122e0a04726f777318022003280b32202e626173" .
    "686f2e7269616b2e6170692e70622e6d6573736167652e5473526f77120c" .
    "0a04646f6e65180320012808225a0a085473476574526571120d0a057461" .
    "626c6518012001280c122e0a036b657918022003280b32212e626173686f" .
    "2e7269616b2e6170692e70622e6d6573736167652e547343656c6c120f0a" .
    "0774696d656f757418032001280d227c0a09547347657452657370123f0a" .
    "07636f6c756d6e7318012003280b322e2e626173686f2e7269616b2e6170" .
    "692e70622e6d6573736167652e5473436f6c756d6e446573637269707469" .
    "6f6e122e0a04726f777318022003280b32202e626173686f2e7269616b2e" .
    "6170692e70622e6d6573736167652e5473526f77228a010a085473507574" .
    "526571120d0a057461626c6518012001280c123f0a07636f6c756d6e7318" .
    "022003280b322e2e626173686f2e7269616b2e6170692e70622e6d657373" .
    "6167652e5473436f6c756d6e4465736372697074696f6e122e0a04726f77" .
    "7318032003280b32202e626173686f2e7269616b2e6170692e70622e6d65" .
    "73736167652e5473526f77220b0a09547350757452657370226a0a085473" .
    "44656c526571120d0a057461626c6518012001280c122e0a036b65791802" .
    "2003280b32212e626173686f2e7269616b2e6170692e70622e6d65737361" .
    "67652e547343656c6c120e0a0676636c6f636b18032001280c120f0a0774" .
    "696d656f757418042001280d220b0a09547344656c52657370225b0a0f54" .
    "73496e746572706f6c6174696f6e120c0a046261736518012001280c123a" .
    "0a0e696e746572706f6c6174696f6e7318022003280b32222e626173686f" .
    "2e7269616b2e6170692e70622e6d6573736167652e52706250616972225a" .
    "0a135473436f6c756d6e4465736372697074696f6e120c0a046e616d6518" .
    "012001280c12350a047479706518022001280e32272e626173686f2e7269" .
    "616b2e6170692e70622e6d6573736167652e5473436f6c756d6e54797065" .
    "22390a055473526f7712300a0563656c6c7318012003280b32212e626173" .
    "686f2e7269616b2e6170692e70622e6d6573736167652e547343656c6c22" .
    "7b0a06547343656c6c12150a0d766172636861725f76616c756518012001" .
    "280c12140a0c73696e7436345f76616c756518022001281212170a0f7469" .
    "6d657374616d705f76616c756518032001281212150a0d626f6f6c65616e" .
    "5f76616c756518042001280812140a0c646f75626c655f76616c75651805" .
    "20012801222f0a0d54734c6973744b657973526571120d0a057461626c65" .
    "18012001280c120f0a0774696d656f757418022001280d224e0a0e54734c" .
    "6973744b65797352657370122e0a046b65797318012003280b32202e6261" .
    "73686f2e7269616b2e6170692e70622e6d6573736167652e5473526f7712" .
    "0c0a04646f6e65180220012808228b010a0d5473436f7665726167655265" .
    "7112390a05717565727918012001280b322a2e626173686f2e7269616b2e" .
    "6170692e70622e6d6573736167652e5473496e746572706f6c6174696f6e" .
    "120d0a057461626c6518022001280c12150a0d7265706c6163655f636f76" .
    "657218032001280c12190a11756e617661696c61626c655f636f76657218" .
    "042003280c224d0a0e5473436f76657261676552657370123b0a07656e74" .
    "7269657318012003280b322a2e626173686f2e7269616b2e6170692e7062" .
    "2e6d6573736167652e5473436f766572616765456e74727922750a0f5473" .
    "436f766572616765456e747279120a0a02697018012001280c120c0a0470" .
    "6f727418022001280d12150a0d636f7665725f636f6e7465787418032001" .
    "280c12310a0572616e676518042001280b32222e626173686f2e7269616b" .
    "2e6170692e70622e6d6573736167652e547352616e67652293010a075473" .
    "52616e676512120a0a6669656c645f6e616d6518012001280c12130a0b6c" .
    "6f7765725f626f756e64180220012812121d0a156c6f7765725f626f756e" .
    "645f696e636c757369766518032001280812130a0b75707065725f626f75" .
    "6e64180420012812121d0a1575707065725f626f756e645f696e636c7573" .
    "697665180520012808120c0a046465736318062001280c2a4f0a0c547343" .
    "6f6c756d6e54797065120b0a07564152434841521000120a0a0653494e54" .
    "36341001120a0a06444f55424c451002120d0a0954494d455354414d5010" .
    "03120b0a07424f4f4c45414e100442230a17636f6d2e626173686f2e7269" .
    "616b2e70726f746f62756642085269616b54735042620670726f746f33"
));

