<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class MapField extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $type = 0;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\MapField_MapFieldType::class);
        $this->type = $var;
    }

}

class MapField_MapFieldType
{
    const DEFAULT = 0;
    const COUNTER = 1;
    const SET = 2;
    const REGISTER = 3;
    const FLAG = 4;
    const MAP = 5;
}

class MapEntry extends \Google\Protobuf\Internal\Message
{
    private $field = null;
    private $counter_value = 0;
    private $set_value;
    private $register_value = '';
    private $flag_value = false;
    private $map_value;

    public function getField()
    {
        return $this->field;
    }

    public function setField(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\MapField::class);
        $this->field = $var;
    }

    public function getCounterValue()
    {
        return $this->counter_value;
    }

    public function setCounterValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->counter_value = $var;
    }

    public function getSetValue()
    {
        return $this->set_value;
    }

    public function setSetValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->set_value = $var;
    }

    public function getRegisterValue()
    {
        return $this->register_value;
    }

    public function setRegisterValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->register_value = $var;
    }

    public function getFlagValue()
    {
        return $this->flag_value;
    }

    public function setFlagValue($var)
    {
        GPBUtil::checkBool($var);
        $this->flag_value = $var;
    }

    public function getMapValue()
    {
        return $this->map_value;
    }

    public function setMapValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapEntry::class);
        $this->map_value = $var;
    }

}

class DtFetchReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $type = '';
    private $r = 0;
    private $pr = 0;
    private $basic_quorum = false;
    private $notfound_ok = false;
    private $timeout = 0;
    private $sloppy_quorum = false;
    private $n_val = 0;
    private $include_context = false;

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getR()
    {
        return $this->r;
    }

    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;
    }

    public function getPr()
    {
        return $this->pr;
    }

    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;
    }

    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    public function setBasicQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->basic_quorum = $var;
    }

    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    public function setNotfoundOk($var)
    {
        GPBUtil::checkBool($var);
        $this->notfound_ok = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;
    }

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getIncludeContext()
    {
        return $this->include_context;
    }

    public function setIncludeContext($var)
    {
        GPBUtil::checkBool($var);
        $this->include_context = $var;
    }

}

class DtValue extends \Google\Protobuf\Internal\Message
{
    private $counter_value = 0;
    private $set_value;
    private $map_value;
    private $hll_value = 0;

    public function getCounterValue()
    {
        return $this->counter_value;
    }

    public function setCounterValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->counter_value = $var;
    }

    public function getSetValue()
    {
        return $this->set_value;
    }

    public function setSetValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->set_value = $var;
    }

    public function getMapValue()
    {
        return $this->map_value;
    }

    public function setMapValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapEntry::class);
        $this->map_value = $var;
    }

    public function getHllValue()
    {
        return $this->hll_value;
    }

    public function setHllValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->hll_value = $var;
    }

}

class DtFetchResp extends \Google\Protobuf\Internal\Message
{
    private $context = '';
    private $type = 0;
    private $value = null;

    public function getContext()
    {
        return $this->context;
    }

    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\DtFetchResp_DataType::class);
        $this->type = $var;
    }

    public function getValue()
    {
        return $this->value;
    }

    public function setValue(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\DtValue::class);
        $this->value = $var;
    }

}

class DtFetchResp_DataType
{
    const DEFAULT = 0;
    const COUNTER = 1;
    const SET = 2;
    const MAP = 3;
    const HLL = 4;
}

class CounterOp extends \Google\Protobuf\Internal\Message
{
    private $increment = 0;

    public function getIncrement()
    {
        return $this->increment;
    }

    public function setIncrement($var)
    {
        GPBUtil::checkInt64($var);
        $this->increment = $var;
    }

}

class SetOp extends \Google\Protobuf\Internal\Message
{
    private $adds;
    private $removes;

    public function getAdds()
    {
        return $this->adds;
    }

    public function setAdds(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->adds = $var;
    }

    public function getRemoves()
    {
        return $this->removes;
    }

    public function setRemoves(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->removes = $var;
    }

}

class HllOp extends \Google\Protobuf\Internal\Message
{
    private $adds;

    public function getAdds()
    {
        return $this->adds;
    }

    public function setAdds(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->adds = $var;
    }

}

class MapUpdate extends \Google\Protobuf\Internal\Message
{
    private $field = null;
    private $counter_op = null;
    private $set_op = null;
    private $register_op = '';
    private $flag_op = 0;
    private $map_op = null;

    public function getField()
    {
        return $this->field;
    }

    public function setField(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\MapField::class);
        $this->field = $var;
    }

    public function getCounterOp()
    {
        return $this->counter_op;
    }

    public function setCounterOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\CounterOp::class);
        $this->counter_op = $var;
    }

    public function getSetOp()
    {
        return $this->set_op;
    }

    public function setSetOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\SetOp::class);
        $this->set_op = $var;
    }

    public function getRegisterOp()
    {
        return $this->register_op;
    }

    public function setRegisterOp($var)
    {
        GPBUtil::checkString($var, False);
        $this->register_op = $var;
    }

    public function getFlagOp()
    {
        return $this->flag_op;
    }

    public function setFlagOp($var)
    {
        GPBUtil::checkEnum($var, \Basho\Riak\Api\Pb\Message\MapUpdate_FlagOp::class);
        $this->flag_op = $var;
    }

    public function getMapOp()
    {
        return $this->map_op;
    }

    public function setMapOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\MapOp::class);
        $this->map_op = $var;
    }

}

class MapUpdate_FlagOp
{
    const DEFAULT = 0;
    const ENABLE = 1;
    const DISABLE = 2;
}

class MapOp extends \Google\Protobuf\Internal\Message
{
    private $removes;
    private $updates;

    public function getRemoves()
    {
        return $this->removes;
    }

    public function setRemoves(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapField::class);
        $this->removes = $var;
    }

    public function getUpdates()
    {
        return $this->updates;
    }

    public function setUpdates(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapUpdate::class);
        $this->updates = $var;
    }

}

class DtOp extends \Google\Protobuf\Internal\Message
{
    private $counter_op = null;
    private $set_op = null;
    private $map_op = null;
    private $hll_op = null;

    public function getCounterOp()
    {
        return $this->counter_op;
    }

    public function setCounterOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\CounterOp::class);
        $this->counter_op = $var;
    }

    public function getSetOp()
    {
        return $this->set_op;
    }

    public function setSetOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\SetOp::class);
        $this->set_op = $var;
    }

    public function getMapOp()
    {
        return $this->map_op;
    }

    public function setMapOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\MapOp::class);
        $this->map_op = $var;
    }

    public function getHllOp()
    {
        return $this->hll_op;
    }

    public function setHllOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\HllOp::class);
        $this->hll_op = $var;
    }

}

class DtUpdateReq extends \Google\Protobuf\Internal\Message
{
    private $bucket = '';
    private $key = '';
    private $type = '';
    private $context = '';
    private $op = null;
    private $w = 0;
    private $dw = 0;
    private $pw = 0;
    private $return_body = false;
    private $timeout = 0;
    private $sloppy_quorum = false;
    private $n_val = 0;
    private $include_context = false;

    public function getBucket()
    {
        return $this->bucket;
    }

    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;
    }

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;
    }

    public function getContext()
    {
        return $this->context;
    }

    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;
    }

    public function getOp()
    {
        return $this->op;
    }

    public function setOp(&$var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\DtOp::class);
        $this->op = $var;
    }

    public function getW()
    {
        return $this->w;
    }

    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;
    }

    public function getDw()
    {
        return $this->dw;
    }

    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;
    }

    public function getPw()
    {
        return $this->pw;
    }

    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;
    }

    public function getReturnBody()
    {
        return $this->return_body;
    }

    public function setReturnBody($var)
    {
        GPBUtil::checkBool($var);
        $this->return_body = $var;
    }

    public function getTimeout()
    {
        return $this->timeout;
    }

    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;
    }

    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;
    }

    public function getNVal()
    {
        return $this->n_val;
    }

    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;
    }

    public function getIncludeContext()
    {
        return $this->include_context;
    }

    public function setIncludeContext($var)
    {
        GPBUtil::checkBool($var);
        $this->include_context = $var;
    }

}

class DtUpdateResp extends \Google\Protobuf\Internal\Message
{
    private $key = '';
    private $context = '';
    private $counter_value = 0;
    private $set_value;
    private $map_value;
    private $hll_value = 0;

    public function getKey()
    {
        return $this->key;
    }

    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;
    }

    public function getContext()
    {
        return $this->context;
    }

    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;
    }

    public function getCounterValue()
    {
        return $this->counter_value;
    }

    public function setCounterValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->counter_value = $var;
    }

    public function getSetValue()
    {
        return $this->set_value;
    }

    public function setSetValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::BYTES);
        $this->set_value = $var;
    }

    public function getMapValue()
    {
        return $this->map_value;
    }

    public function setMapValue(&$var)
    {
        GPBUtil::checkRepeatedField($var, GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapEntry::class);
        $this->map_value = $var;
    }

    public function getHllValue()
    {
        return $this->hll_value;
    }

    public function setHllValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->hll_value = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0aab110a0d7269616b5f64742e70726f746f1219626173686f2e7269616b" .
    "2e6170692e70622e6d65737361676522ac010a084d61704669656c64120c" .
    "0a046e616d6518012001280c123e0a047479706518022001280e32302e62" .
    "6173686f2e7269616b2e6170692e70622e6d6573736167652e4d61704669" .
    "656c642e4d61704669656c645479706522520a0c4d61704669656c645479" .
    "7065120b0a0744454641554c541000120b0a07434f554e54455210011207" .
    "0a035345541002120c0a085245474953544552100312080a04464c414710" .
    "0412070a034d4150100522cc010a084d6170456e74727912320a05666965" .
    "6c6418012001280b32232e626173686f2e7269616b2e6170692e70622e6d" .
    "6573736167652e4d61704669656c6412150a0d636f756e7465725f76616c" .
    "756518022001281212110a097365745f76616c756518032003280c12160a" .
    "0e72656769737465725f76616c756518042001280c12120a0a666c61675f" .
    "76616c756518052001280812360a096d61705f76616c756518062003280b" .
    "32232e626173686f2e7269616b2e6170692e70622e6d6573736167652e4d" .
    "6170456e74727922c9010a0a44744665746368526571120e0a066275636b" .
    "657418012001280c120b0a036b657918022001280c120c0a047479706518" .
    "032001280c12090a017218042001280d120a0a02707218052001280d1214" .
    "0a0c62617369635f71756f72756d18062001280812130a0b6e6f74666f75" .
    "6e645f6f6b180720012808120f0a0774696d656f757418082001280d1215" .
    "0a0d736c6f7070795f71756f72756d180920012808120d0a056e5f76616c" .
    "180a2001280d12170a0f696e636c7564655f636f6e74657874180b200128" .
    "08227e0a07447456616c756512150a0d636f756e7465725f76616c756518" .
    "012001281212110a097365745f76616c756518022003280c12360a096d61" .
    "705f76616c756518032003280b32232e626173686f2e7269616b2e617069" .
    "2e70622e6d6573736167652e4d6170456e74727912110a09686c6c5f7661" .
    "6c756518042001280422d1010a0b4474466574636852657370120f0a0763" .
    "6f6e7465787418012001280c123d0a047479706518022001280e322f2e62" .
    "6173686f2e7269616b2e6170692e70622e6d6573736167652e4474466574" .
    "6368526573702e446174615479706512310a0576616c756518032001280b" .
    "32222e626173686f2e7269616b2e6170692e70622e6d6573736167652e44" .
    "7456616c7565223f0a084461746154797065120b0a0744454641554c5410" .
    "00120b0a07434f554e544552100112070a03534554100212070a034d4150" .
    "100312070a03484c4c1004221e0a09436f756e7465724f7012110a09696e" .
    "6372656d656e7418012001281222260a055365744f70120c0a0461646473" .
    "18012003280c120f0a0772656d6f76657318022003280c22150a05486c6c" .
    "4f70120c0a046164647318012003280c22e0020a094d6170557064617465" .
    "12320a056669656c6418012001280b32232e626173686f2e7269616b2e61" .
    "70692e70622e6d6573736167652e4d61704669656c6412380a0a636f756e" .
    "7465725f6f7018022001280b32242e626173686f2e7269616b2e6170692e" .
    "70622e6d6573736167652e436f756e7465724f7012300a067365745f6f70" .
    "18032001280b32202e626173686f2e7269616b2e6170692e70622e6d6573" .
    "736167652e5365744f7012130a0b72656769737465725f6f701804200128" .
    "0c123c0a07666c61675f6f7018052001280e322b2e626173686f2e726961" .
    "6b2e6170692e70622e6d6573736167652e4d61705570646174652e466c61" .
    "674f7012300a066d61705f6f7018062001280b32202e626173686f2e7269" .
    "616b2e6170692e70622e6d6573736167652e4d61704f70222e0a06466c61" .
    "674f70120b0a0744454641554c541000120a0a06454e41424c451001120b" .
    "0a0744495341424c45100222740a054d61704f7012340a0772656d6f7665" .
    "7318012003280b32232e626173686f2e7269616b2e6170692e70622e6d65" .
    "73736167652e4d61704669656c6412350a07757064617465731802200328" .
    "0b32242e626173686f2e7269616b2e6170692e70622e6d6573736167652e" .
    "4d617055706461746522d6010a0444744f7012380a0a636f756e7465725f" .
    "6f7018012001280b32242e626173686f2e7269616b2e6170692e70622e6d" .
    "6573736167652e436f756e7465724f7012300a067365745f6f7018022001" .
    "280b32202e626173686f2e7269616b2e6170692e70622e6d657373616765" .
    "2e5365744f7012300a066d61705f6f7018032001280b32202e626173686f" .
    "2e7269616b2e6170692e70622e6d6573736167652e4d61704f7012300a06" .
    "686c6c5f6f7018042001280b32202e626173686f2e7269616b2e6170692e" .
    "70622e6d6573736167652e486c6c4f7022fe010a0b447455706461746552" .
    "6571120e0a066275636b657418012001280c120b0a036b65791802200128" .
    "0c120c0a047479706518032001280c120f0a07636f6e7465787418042001" .
    "280c122b0a026f7018052001280b321f2e626173686f2e7269616b2e6170" .
    "692e70622e6d6573736167652e44744f7012090a017718062001280d120a" .
    "0a02647718072001280d120a0a02707718082001280d12130a0b72657475" .
    "726e5f626f6479180920012808120f0a0774696d656f7574180a2001280d" .
    "12150a0d736c6f7070795f71756f72756d180b20012808120d0a056e5f76" .
    "616c180c2001280d12170a0f696e636c7564655f636f6e74657874180d20" .
    "01280822a1010a0c447455706461746552657370120b0a036b6579180120" .
    "01280c120f0a07636f6e7465787418022001280c12150a0d636f756e7465" .
    "725f76616c756518032001281212110a097365745f76616c756518042003" .
    "280c12360a096d61705f76616c756518052003280b32232e626173686f2e" .
    "7269616b2e6170692e70622e6d6573736167652e4d6170456e7472791211" .
    "0a09686c6c5f76616c756518062001280442230a17636f6d2e626173686f" .
    "2e7269616b2e70726f746f62756642085269616b44745042620670726f74" .
    "6f33"
));

